<<eval=TRUE, echo=TRUE>>=
...skipping...
\subsection{S4 objects in R}
In the last example, we have used Gmedian and  Rmedian data. However, we should have also considered the background signal. The problem is that we should have created four vectors (or four matrix if several microarrays were analyzed). As it is rather difficult to manipulate the four matrices we will design a class ("micBatch") that will contain all information within a single object.

<<fig=T, eval=TRUE, echo=TRUE,keep.source=TRUE>>=
# micBatch
# "representation" corresponds to all attributes of the object:
# "prototype" corresponds corresponds to default values:

setClass("micBatch",
    representation(
        R="matrix",
        G="matrix",
        Rb="matrix",
        Gb="matrix",
        phenotype="matrix",
        genes="character",
        description="character"),
    prototype=list(
        R=matrix(nr=0,nc=0),
        G=matrix(nr=0,nc=0),
        Rb=matrix(nr=0,nc=0),
        Gb=matrix(nr=0,nc=0),
        phenotype=matrix(nr=0,nc=0),
        description=new("character")
            )
    )

myMA=new("micBatch")

slotNames(myMA)
getClassDef("micBatch")

myMA@R <- matrix(rnorm(20),nc=5)
myMA@R <- matrix(rnorm(20),nc=5)
myMA@Rb <- matrix(rnorm(20),nc=5)
myMA@Gb <- matrix(rnorm(20),nc=5)

# let's visualize the object.
# (implicit call to the "show" method).
myMA

# Let's define the method "show" for an object of class
# micBatch

setMethod("show", signature("micBatch"),
       function(object){
        cat("An instance of class micBatch\n")
        cat("Nb sample=", ncol(object@R),"\n")
        cat("Nb genes=", nrow(object@R),"\n")
})

# Let's call the "show" method
myMA
@

As shown in this example we can easily define methods for the class \Rfunction{micBatch}. Just remind that we could have define a method for the "[" operator. This would have been particularly interesting to extract rows (genes) and columns (arrays) of the object.
